stages:
  - run-pipeline

run-go-pipeline:
  stage: run-pipeline
  only:
    - dev
    - staging
    - master
  trigger:
    include:
      - project: 'global/ci-pipelines'
        ref: 'master'
        file: 'nodejs-pipeline.yml'
    strategy: depend

